
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: chat_password 
      POSTGRES_USER: chat_user         
      POSTGRES_DB: chat_db              
    env_file: ./server/.env 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data: